In [2]:
import numpy as np
import pandas as pd

ser_1 = pd.Series(range(5))
ser_2 = pd.Series(list('abcde'))

In [3]:
ser_1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [4]:
ser_2

0    a
1    b
2    c
3    d
4    e
dtype: object

In [9]:
df_1 = pd.concat([ser_1 ,ser_2],axis=0)
df_1

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

In [11]:
df_2 = pd.concat([ser_1, ser_2], axis=1)
df_2

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [15]:
data_df_1 = pd.DataFrame(df_1)
data_df_1

   0
0  0
1  1
2  2
3  3
4  4
0  a
1  b
2  c
3  d
4  e

In [17]:
data_df_2 = pd.DataFrame(df_2)
data_df_2

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e